language: python
dist: xenial
python:
  - '2.7'
  - '3.7'
  - '3.8'
install:
  - pip install tox-travis
script:
  - tox -- --cov-report=xml
  - bash <(curl -s https://codecov.io/bash)
stages:
  - test
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: test
      python: '3.7'
      install:
        - pip install pipenv
      script:
        - pipenv install --deploy --dev
        - pipenv run pre-commit run --all-files
    - stage: deploy
      python: '3.7'
      install:
        - pip install pipenv
      script:
        - pipenv install --deploy --dev --system
      deploy:
        - provider: pypi
          user: __token__
          password:
            secure: iJF66w38XlqoFRNgKVvgu6jYUGgQk9Uln03ZRGFy/Trr1LNZOaeIu+3A5yLuHeIGydps01iL1V8PUl0Mh78W79s3Yar6OQ3JObWAPLT6N5F9tZv80C8i0rN02rbPx2pPJMtSAIznS72zr67R7Zsx73T7KuBnVil/+tgcEF2x34Mcgb9/YAp/fOghzriDJKhQs+Sqd0xHWsS9kDL9HtYJcNDt4SRnxX5b7aosSLZQ3YrVZ64cqyGh4Hi/U/phd7KIoniDyLPn23h5LyKsOuOis59Q5t7IUpFnMXyAWiNXlCzUAiekUeSaWfaPhOiHhjRFuJwr9gRC53H7/t29AumILwR1g3xVq5EEpQbcQQvw/5S6U6XCcOHUBA9BImPkoOSQztwWGMCUrqgZnTQQI6/311NhH6cm+VOwP38eZ7nUQL4E5ZtC5fK3qpZwuwqKo2QNH8uWPf+OJ+IfpW1b+3wYDiP5Nb5AssskIgg6okczFr42ZWApo/TO9OnwF01j202RJnUnYwIF2MQzCdTzxqotAw1YbhOHBXjpssWXAsYRennJtMbMtkxfz1bc67hHvxFAthNdGOs5N5ZP0rAJktU4wYqbgEsiIcSRBog065KVU0Om1yT58pnvvJs5rIjJsogOE9Ume2xXhpdo2jbmIKBmV4rmWN+fYCzJ/Scc45DTPlM=
          distributions: sdist bdist_wheel
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key:
            secure: suZbSCaKIIA7zZcWftCcoeQ5x/nJQZUeuoCRvpof1cgL442UcGhxuIpQw+dx4Tr1iV7FtvR47MRcJqz2Yd8FTYZjkNQhk0iX4XMZDvXPsTVpYSyblcZgyHorwUdpb1dJqY1R018MmA4B+lfmU9q75KL0wa6+1H9byucI234oYO2FBddg1uyr6Xr1qiMKJZuskVQ5SKREVhjBgue3WuJmn/z04mcszuo5VFLusKnMyZi9UXKu/QEUGGoJcox1s3du3hMJn4l+6w4UTyGBQyibXVMOeu01/rPsTRCOeKuy4V6zMBWgd+QgW67aNkUilsmDtNlloIdhydILVQcsByaKF4WXrWSocZK7XVFmEsJtBA96nmisvQ/gFRk0yCirAEhFuWFoIcQgB5Aky23uDrd1g8U1zq5TySBzb0B8ZM1rwIAgrsxFupJUIcc5oCB1S2Lh7Pk34kzGNL9gIZVfZzvxN8GG6GhX5Ja3yYLiABisjuxQrY2TrR2LFDrCzzEz8Dwn4mvhHlCH/YPsfn42heBUbCtR0UH6FSNZwO2WKb8RkeeC8nDJl0Gw+2qxMQbmr923WeCmMW79cKAJTwTY5g3iEF7bzIek2GBmbh1r3IingYGC4kFvvS8eBObR1bgbOLlqim8Ig3T46e5BoUv/1PWI/xicdm2vH3AGeoupgiP8H9o=
          skip_cleanup: true
          on:
            tags: true
