language: python
dist: xenial
python:
  - '2.7'
  - '3.7'
  - '3.8'
install:
  - pip install tox-travis
script:
  - tox -- --cov-report=xml
  - bash <(curl -s https://codecov.io/bash)
stages:
  - test
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: test
      python: '3.7'
      install:
        - pip install pipenv
      script:
        - pipenv install --deploy --dev
        - pipenv run pre-commit run --all-files
    - stage: deploy
      python: '3.7'
      install:
        - pip install pipenv
      script:
        - pipenv install --deploy --dev --system
      deploy:
        - provider: pypi
          user: __token__
          password:
            secure: H5Xk7EoA0lnL9X3EC9XcRAIkpsROa4mhkBUBHCIiDsZR5cYk+I18VVDpWEPm5pnVfhaqOBxXTNx4razhlzqUAGYUWPztlEflVAWAQ14XMB9sT1my5bqrXjEfjb1E0ucT46hLVKeB/DNoXexEOwQOJUuhvFm3mu2padIeMD79nKMCwkCjAIbskZ8pjaVa6sVQc8oHfCpqqtJcuFTibqhC29ZDijm0ph2OhmX7LtJfB2ozNOhumLt8Un9Ze4VqubQj5xKo1/m7MDVHnCLYosXGR6gz94q5bwQuZsm5TT96o59TME2kjk4FGMVKxEuTPQG+zM1qU+F48nPie9KSyMh295jD3bhph8jXDWuLZTIfYu2fhCRPAhJCCWdZrsEpgLgpIQOM4ZNxrwA2/V3GOps5I78+LjXmHY5TGlf77l3ez6yZ7FYPK4Fhu6bWD7jVT/BnzwbM80n8QqUYaJ4Dz1qESsZ8A3zUSKYmpBpp0OHnWBD+y03Em/HXvG2NJw1ko5cc9g+Lxc4nXPzjmNRtikL6i/rXRLXoAiuZvVXkk01YSDBXAk2cB/uKJvgTEIi/w0iVXIOCJHb4EmMrfNcxDu9BbSVGSCwWGVNiGcvAVNAOk0ry0DjARANE4eX/hNUqq+49tSnsIOuswqvhjKBiKYV+WpvVRdpmk3jfXj5/37g4QVs=
          distributions: sdist bdist_wheel
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key:
            secure: suZbSCaKIIA7zZcWftCcoeQ5x/nJQZUeuoCRvpof1cgL442UcGhxuIpQw+dx4Tr1iV7FtvR47MRcJqz2Yd8FTYZjkNQhk0iX4XMZDvXPsTVpYSyblcZgyHorwUdpb1dJqY1R018MmA4B+lfmU9q75KL0wa6+1H9byucI234oYO2FBddg1uyr6Xr1qiMKJZuskVQ5SKREVhjBgue3WuJmn/z04mcszuo5VFLusKnMyZi9UXKu/QEUGGoJcox1s3du3hMJn4l+6w4UTyGBQyibXVMOeu01/rPsTRCOeKuy4V6zMBWgd+QgW67aNkUilsmDtNlloIdhydILVQcsByaKF4WXrWSocZK7XVFmEsJtBA96nmisvQ/gFRk0yCirAEhFuWFoIcQgB5Aky23uDrd1g8U1zq5TySBzb0B8ZM1rwIAgrsxFupJUIcc5oCB1S2Lh7Pk34kzGNL9gIZVfZzvxN8GG6GhX5Ja3yYLiABisjuxQrY2TrR2LFDrCzzEz8Dwn4mvhHlCH/YPsfn42heBUbCtR0UH6FSNZwO2WKb8RkeeC8nDJl0Gw+2qxMQbmr923WeCmMW79cKAJTwTY5g3iEF7bzIek2GBmbh1r3IingYGC4kFvvS8eBObR1bgbOLlqim8Ig3T46e5BoUv/1PWI/xicdm2vH3AGeoupgiP8H9o=
          skip_cleanup: true
          on:
            tags: true
